### ISSUE TITLE
mention how to handle errors in readme

### ISSUE THREAD

**Issue by benkaiser** [ranm8/requestify#22]
I am using this library to make requests and had to go trawling through the code to work out what was happening when a http error happened. Could it be added to the readme like so:

> ### Handling Errors
> to handle errors, pass a second function to the `then` call:
>```
>requestify.post(url, data).then(successFunction, errorFunction);
>```

Might save people some time trying to work it out.

**Comment by angelxmoreno** [comment]
Could you please submit a PR?

**Comment by benkaiser** [comment]
PR submitted. I assumed the `v0.2.0` branch was the default (considering that's the `README.md` that is show publicly).

**Comment by angelxmoreno** [comment]
:+1:
