### ISSUE TITLE
cache never expries

### ISSUE THREAD

**Issue by jinweilin** [ranm8/requestify#23]
This line 
if (!data || (data.created + request.cache.expires > new Date().getTime())) {

should be change 
if (!data || (data.created + request.cache.expires < new Date().getTime())) {

In Requestify.js, Line : 155

**Comment by blanchma** [comment]
Same here.

**Comment by jack13** [comment]
Date().getTime() returns milliseconds, and according to readme the expires argument is in seconds
so the condition should be:

`if (!data || (data.created + request.cache.expires*1000 < new Date().getTime())) {`

**Comment by ran-y** [comment]
fixed with 4a30bdde0e3273014a64b848c810e04d5b73c533
