### ISSUE TITLE
Error thrown in NodeJs 0.12.0

### ISSUE THREAD

**Issue by rgeraldporter** [ranm8/requestify#25]
node_modules/requestify/node_modules/jquery/node_modules/jsdom/lib/jsdom/level1/core.js:418
    set nodeName() { throw new core.DOMException();},
                 ^
    SyntaxError: Unexpected token )

JsDOM actually fixed this issue a while back, and jQuery no longer uses JsDOM. Probably need to upgrade the jQuery version to run in v0.12 of Node.

**Comment by bweston92** [comment]
Same issue here. Any update?

**Comment by bweston92** [comment]
We need to update jQuery.

**Comment by thedug** [comment]
Any eta on when this will be available?

**Comment by dermotos** [comment]
I'm also experiencing this.

**Comment by bweston92** [comment]
I've made a PR it is today with jQuery with one of the dependencies.



—

**Comment by ranm8** [comment]
Thanks. Fixed on 0.1.17. Update to latest 0.1.x and it will be ok.

Anyway, I'm planning to remove jQuery from core at version 0.2.0 and distribute as a separate project that extends Requestify.
Hopefully the version will be delivered in the next few weeks.

Closing...

**Comment by seemasohoni** [comment]
Hi there,

I have downloaded NodeJs 0.12.0 and after trying to compile using grunt-cli I see the following exception:
...grunt release
Loading "cancompile.js" tasks...ERROR
>> SyntaxError: /Users/../../content/catalog/node_modules/can-compile/node_modules/jsdom/lib/jsdom/level1/core.js:450
>>   set childNodes() { throw new core.DOMException();},
>>                  ^
>> Unexpected token )
Warning: Task "cancompile" not found. Use --force to continue.

I aded the following to my jquery 's package.json..
However I still see the same problem.

Couple of questions:
1. One of the above solutions is to bump up the jquery version in package.json, but which package.son are you referring to, should there be one under nom something?
2. The version of query that I have installed is 2.1.3, i.e > 1.8.3

Can you please help?

**Comment by andersonmadeira** [comment]
Using nodejs 12.1 here and the issue still persists.
