### ISSUE TITLE
How to include POST parameters ?

### ISSUE THREAD

**Issue by Ratnesh-Github** [ranm8/requestify#27]

**Comment by Ratnesh-Github** [comment]
Can someone tell how to include post parameters through requestify ?

**Comment by Ratnesh-Github** [comment]
I was able to include post parameters by changing the data type field.

**Comment by hiagodotme** [comment]
Hello, to receive the parameter in $_POST in php it is necessary to send a `form-url-encoded` request. According to the `requestify/lib/request.js` file in line 28 the if the dataType is not defined it defaults to the JSON value and tries to serialize its object. Here's a way to send the request as form-url-encoded.

```
var requestify = require('requestify');
requestify.post('https://your_url/your_page.php`, {name: "Hiago", age: 23}, {
    dataType: 'form-url-encoded'
}).then(function(res) {
    console.log(res);
});
```
By doing this you can retrieve the information with $_POST["name"] and $_POST["age"]
