### ISSUE TITLE
Support various Promise libraries

### ISSUE THREAD

**Issue by JAForbes** [ranm8/requestify#35]
Any chance of supporting multiple Promise libraries?

I've got bluebird in my project already, and I'm curious if I can just override some internal property and all will be well?

**Comment by angelxmoreno** [comment]
AFAIK, Q and Bluebird share similar but not identical APIs. Using them interchangeably does not seem like a simple task. The bigger question would be can we switch to bluebird promises since Q has so many issues on its own. #37 being one of them.
