### ISSUE TITLE
Incorrect content length when body contains unicode characters

### ISSUE THREAD

**Issue by osuushi** [ranm8/requestify#42]
Because `Request.prototype.getContentLength` uses string.length, requestify breaks on unicode bodies. It looks like this is fixed in the 0.2.0 branch, which is not published to npm. Any timetable on that?

**Comment by mutekinootoko** [comment]
+1

**Comment by Niyarlatotep** [comment]
+1

**Comment by Alex-Werner** [comment]
Hi. 
I came here as I had a struggle with requestify and international characters / accent. 
Sending : {interest:"Honoré De Balzac"} made my server reject HTTP400 the call (

**Comment by Alex-Werner** [comment]
@ran-y That's a freaking good things to hear :D

**Comment by ranm8** [comment]
Version 0.2.0 was released! feel free to update (-: Closing
