### ISSUE TITLE
Trying to send POST payload

### ISSUE THREAD

**Issue by drj-io** [ranm8/requestify#8]
I'm trying to send off a payload, but it's not working.

Sending script: 

```
requestify.post('http://localhost/rest.php',  {test:'123',foo:'bar'})
.then(function(response) {
    // get the response body
    console.log('got response');

    response.getBody();

 res.send(response.body);


});
```

Here's the PHP script that accepts:

```
<?php


print_r($_POST);
```

and returns an empty 

```
Array ( )
```

I get 

```
verbose: Attempted to retry bodyParse as JSON.  But no luck. Error: invalid json, empty body
```

Any ideas?  I hate to go back to using raw express http.request

**Comment by vossavant** [comment]
For the record, ranm8's suggestion worked for me.

**Comment by hiagodotme** [comment]
Hello, to receive the parameter in $_POST in php it is necessary to send a `form-url-encoded` request. According to the `requestify/lib/request.js` file in line 28 the if the dataType is not defined it defaults to the JSON value and tries to serialize its object. Here's a way to send the request as form-url-encoded.

```
var requestify = require('requestify');
requestify.post('https://your_url/your_page.php`, {name: "Hiago", age: 23}, {
    dataType: 'form-url-encoded'
}).then(function(res) {
    console.log(res);
});
```
By doing this you can retrieve the information with $_POST["name"] and $_POST["age"]
